### ISSUE TITLE
只有纲领吗？

### ISSUE THREAD

**Issue by succelever** [the-run-philosophy/run#2]

**Comment by tomieric** [comment]
纲领说新中国人不对滴。

你们润了，就是自由世界的人，不应该叫新中国人，叫道格狲人，也要区分解放前已经去到自由世界的华人。

**Comment by succelever** [comment]
好了好了😅



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月18日(周一) 上午9:19
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [The-Run-Philosophy-Organization/run] 只有纲领吗？ (Issue #2)




 
纲领说新中国人不对滴。
 
你们润了，就是自由世界的人，不应该叫新中国人，叫道格狲人，也要区分解放前已经去到自由世界的华人。
